language: node_js
node_js:
  - "10"
install:
  - yarn install
jobs:
  include:
    - stage: Unit Tests
      script: yarn test:unit
    - stage: Deploy GitHub Pages
      if: branch = master
      script: yarn docs:build
      deploy:
        on:
          branch: master
        provider: pages
        skip-cleanup: true
        local_dir: docs/.vuepress/dist
        github-token: $GITHUB_TOKEN
        repo: dm4t2/vue-currency-input

