language: node_js
node_js:
  - "10"
install:
  - yarn global add vuepress
script:
  - yarn docs:build
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN
  repo: dm4t2/vue-currency-input
